version: '3'
services:
  postgres:
    image: postgres:11.4
    container_name: postgres
    volumes:
      - ./docker-initdb.sh:/docker-entrypoint-initdb.d/docker-initdb.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB_NAME},${POSTGRES_TEST_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    networks:
      - nw

networks:
  nw:
    driver: bridge
