version: '3'
services:
  postgres:
    image: postgres:11.4
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - nw

networks:
  nw:
    driver: bridge
