version: '3'
services:
  api:
    container_name: go_notes_development
    image: go_notes_development:latest
    build: .
    ports: 
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - .:/src
    depends_on:
      - postgres
    networks:
      - nw
    environment:
      - PGPASSWORD=${POSTGRES_DB_PASSWORD}
    command:
      ["./docker-entrypoint.sh", "postgres", "modd"]

volumes:
  api:
